/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export const SelectTile = React.forwardRef(({ x, y, ...props }, ref) => {
  const { nodes } = useGLTF('/models/grass.glb')
  return (
    <group ref={ref} dispose={null} {...props}>
      <mesh geometry={nodes.Mesh_grass_1.geometry}>
        <meshPhongMaterial transparent opacity={0.1} color="gray"/>
      </mesh>
    </group>
  )
});

useGLTF.preload('/models/grass.glb')
