/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function SelectTile({ x, y, ...props }) {
  const group = useRef()
  const { nodes } = useGLTF('/models/grass.glb')
  return (
    <group ref={group} dispose={null} {...props}>
      <mesh geometry={nodes.Mesh_grass_1.geometry}>
        <meshPhongMaterial transparent opacity={0.1} color="gray"/>
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/grass.glb')
