/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/building_sheep.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_building_sheep.geometry} material={materials.dirt} />
      <mesh geometry={nodes.Mesh_building_sheep_1.geometry} material={materials.grass} />
      <mesh geometry={nodes.fence.geometry} material={materials.dirt} position={[-0.48, 0.2, -0.06]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.fence_1.geometry} material={materials.dirt} position={[0.47, 0.2, 0.06]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.fence_2.geometry} material={materials.dirt} position={[0.18, 0.2, -0.44]} rotation={[0, -Math.PI / 6, 0]} />
      <mesh geometry={nodes.fence_3.geometry} material={materials.dirt} position={[-0.18, 0.2, 0.44]} rotation={[-Math.PI, Math.PI / 6, -Math.PI]} />
      <group position={[-0.2, 0.2, -0.22]} rotation={[0, Math.PI / 3, 0]}>
        <mesh geometry={nodes.Mesh_sheep.geometry} material={materials.dark} />
        <mesh geometry={nodes.Mesh_sheep_1.geometry} material={materials.wool} />
      </group>
      <group position={[0.06, 0.2, 0.3]} rotation={[0, Math.PI / 6, 0]}>
        <mesh geometry={nodes.Mesh_sheep.geometry} material={materials.dark} />
        <mesh geometry={nodes.Mesh_sheep_1.geometry} material={materials.wool} />
      </group>
      <group position={[0.32, 0.2, 0.09]} rotation={[0, 0.18, 0]}>
        <mesh geometry={nodes.Mesh_sheep.geometry} material={materials.dark} />
        <mesh geometry={nodes.Mesh_sheep_1.geometry} material={materials.wool} />
      </group>
      <group position={[0.04, 0.2, 0]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.Mesh_sheep.geometry} material={materials.dark} />
        <mesh geometry={nodes.Mesh_sheep_1.geometry} material={materials.wool} />
      </group>
      <group position={[-0.25, 0.2, 0.13]}>
        <mesh geometry={nodes.Mesh_sheep.geometry} material={materials.dark} />
        <mesh geometry={nodes.Mesh_sheep_1.geometry} material={materials.wool} />
      </group>
      <group position={[0.14, 0.2, -0.29]} rotation={[Math.PI, -1.31, Math.PI]}>
        <mesh geometry={nodes.Mesh_sheep.geometry} material={materials.dark} />
        <mesh geometry={nodes.Mesh_sheep_1.geometry} material={materials.wool} />
      </group>
    </group>
  )
}

useGLTF.preload('/building_sheep.glb')
