/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/building_farm.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_building_farm.geometry} material={materials.dirt} />
      <mesh geometry={nodes.Mesh_building_farm_1.geometry} material={materials.grass} />
      <mesh geometry={nodes.fence.geometry} material={materials.dirt} position={[-0.38, 0.2, 0]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.grain.geometry} material={materials.sand} position={[0.05, 0.2, 0.09]} rotation={[0, -Math.PI / 3, 0]} />
      <mesh geometry={nodes.grainBundle.geometry} material={materials.sand} position={[-0.29, 0.2, -0.13]} />
      <mesh geometry={nodes.grainBundle_1.geometry} material={materials.sand} position={[-0.15, 0.2, -0.23]} rotation={[0, -Math.PI / 6, 0]} scale={[1, 0.5, 1]} />
    </group>
  )
}

useGLTF.preload('/building_farm.glb')
