/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/building_village.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_building_village.geometry} material={materials.dirt} />
      <mesh geometry={nodes.Mesh_building_village_1.geometry} material={materials.grass} />
      <group position={[-0.05, 0.2, -0.25]}>
        <mesh geometry={nodes.Mesh_building.geometry} material={materials.roof} />
        <mesh geometry={nodes.Mesh_building_1.geometry} material={materials.wood} />
        <mesh geometry={nodes.Mesh_building_2.geometry} material={materials.dirt} />
      </group>
      <group position={[0.03, 0.2, 0.22]} rotation={[0, Math.PI / 4, 0]}>
        <mesh geometry={nodes.Mesh_building_3.geometry} material={materials.roof} />
        <mesh geometry={nodes.Mesh_building_4.geometry} material={materials.wood} />
        <mesh geometry={nodes.Mesh_building_5.geometry} material={materials.dirt} />
      </group>
      <mesh geometry={nodes.chimney.geometry} material={materials.stone} position={[-0.1, 0.2, 0.09]} rotation={[0, Math.PI / 4, 0]} scale={[1, 0.74, 1]} />
      <mesh geometry={nodes.fence.geometry} material={materials.dirt} position={[0.18, 0.2, -0.44]} rotation={[0, -Math.PI / 6, 0]} />
      <mesh geometry={nodes.fence_1.geometry} material={materials.dirt} position={[0.47, 0.2, 0.06]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Group.geometry} material={materials.dirt} position={[0.21, 0.2, -0.16]} rotation={[0, Math.PI / 6, 0]} scale={[0.74, 1, 0.74]} />
      <mesh geometry={nodes.Group_1.geometry} material={materials.dirt} position={[0.21, 0.2, 0.04]} scale={[0.74, 1, 0.74]} />
      <group position={[-0.29, 0.2, 0.09]} rotation={[0, -0.37, 0]}>
        <mesh geometry={nodes.Mesh_tree.geometry} material={materials.foliage} />
        <mesh geometry={nodes.Mesh_tree_1.geometry} material={materials.wood} />
      </group>
      <group position={[0.35, 0.2, 0.22]} rotation={[0, -0.11, 0]} scale={0.77}>
        <mesh geometry={nodes.Mesh_tree.geometry} material={materials.foliage} />
        <mesh geometry={nodes.Mesh_tree_1.geometry} material={materials.wood} />
      </group>
    </group>
  )
}

useGLTF.preload('/building_village.glb')
