/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/building_mine.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_building_mine.geometry} material={materials.dirt} />
      <mesh geometry={nodes.Mesh_building_mine_1.geometry} material={materials.grass} />
      <group position={[0.08, 0.2, -0.03]}>
        <mesh geometry={nodes.Mesh_mine.geometry} material={materials.dirt} />
        <mesh geometry={nodes.Mesh_mine_1.geometry} material={materials.wood} />
      </group>
      <mesh geometry={nodes.path.geometry} material={materials.dirt} position={[0.33, 0.2, -0.03]} />
      <mesh geometry={nodes.rock.geometry} material={materials.stone} position={[0.13, 0.2, -0.28]} rotation={[0, Math.PI / 6, 0]} scale={[1.33, 1.21, 1.31]} />
      <mesh geometry={nodes.rock_1.geometry} material={materials.stone} position={[0.27, 0.2, 0.21]} rotation={[0, 1.4, 0]} scale={[1.33, 0.61, 1.31]} />
      <mesh geometry={nodes.rockLarge.geometry} material={materials.stone} position={[-0.16, 0.2, -0.02]} scale={0.89} />
      <group position={[0.11, 0.2, 0.35]} rotation={[0, 0.15, 0]} scale={0.77}>
        <mesh geometry={nodes.Mesh_tree.geometry} material={materials.foliage} />
        <mesh geometry={nodes.Mesh_tree_1.geometry} material={materials.wood} />
      </group>
      <group position={[0.04, 0.2, -0.46]} rotation={[0, Math.PI / 2, 0]} scale={0.62}>
        <mesh geometry={nodes.Mesh_tree.geometry} material={materials.foliage} />
        <mesh geometry={nodes.Mesh_tree_1.geometry} material={materials.wood} />
      </group>
    </group>
  )
}

useGLTF.preload('/building_mine.glb')
