/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/building_smelter.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_building_smelter.geometry} material={materials.dirt} />
      <mesh geometry={nodes.Mesh_building_smelter_1.geometry} material={materials.grass} />
      <group position={[-0.07, 0.2, 0.2]}>
        <mesh geometry={nodes.Mesh_building.geometry} material={materials.roof} />
        <mesh geometry={nodes.Mesh_building_1.geometry} material={materials.wood} />
        <mesh geometry={nodes.Mesh_building_2.geometry} material={materials.dirt} />
      </group>
      <mesh geometry={nodes.chimney.geometry} material={materials.stone} position={[-0.07, 0.2, 0.39]} />
      <group position={[-0.07, 0.2, -0.14]} rotation={[0, 0.26, 0]}>
        <mesh geometry={nodes.Mesh_furnace.geometry} material={materials.stone} />
        <mesh geometry={nodes.Mesh_furnace_1.geometry} material={materials.stoneDark} />
        <mesh geometry={nodes.Mesh_furnace_2.geometry} material={materials.dark} />
      </group>
      <mesh geometry={nodes.path.geometry} material={materials.dirt} position={[0.21, 0.2, 0.13]} scale={[0.74, 1, 0.74]} />
      <mesh geometry={nodes.path_1.geometry} material={materials.dirt} position={[0.25, 0.2, -0.25]} />
      <mesh geometry={nodes.rock.geometry} material={materials.stone} position={[-0.2, 0.2, -0.34]} rotation={[0, Math.PI / 6, 0]} scale={[1.11, 0.66, 1.09]} />
      <mesh geometry={nodes.rock_1.geometry} material={materials.stone} position={[0.19, 0.2, 0.33]} rotation={[0, Math.PI / 6, 0]} scale={[1.11, 0.96, 1.09]} />
      <group position={[0.01, 0.2, -0.46]} rotation={[0, 1.31, 0]} scale={0.62}>
        <mesh geometry={nodes.Mesh_tree.geometry} material={materials.foliage} />
        <mesh geometry={nodes.Mesh_tree_1.geometry} material={materials.wood} />
      </group>
      <group position={[0.36, 0.2, 0.21]} rotation={[0, 1.31, 0]} scale={0.62}>
        <mesh geometry={nodes.Mesh_tree_2.geometry} material={materials.foliage} />
        <mesh geometry={nodes.Mesh_tree_3.geometry} material={materials.wood} />
      </group>
      <group position={[-0.4, 0.2, -0.25]} rotation={[0, 0.15, 0]} scale={0.77}>
        <mesh geometry={nodes.Mesh_tree_4.geometry} material={materials.foliage} />
        <mesh geometry={nodes.Mesh_tree_5.geometry} material={materials.wood} />
      </group>
    </group>
  )
}

useGLTF.preload('/building_smelter.glb')
