/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/building_mill.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_building_mill.geometry} material={materials.dirt} />
      <mesh geometry={nodes.Mesh_building_mill_1.geometry} material={materials.grass} />
      <group position={[0.04, 0.2, 0]}>
        <mesh geometry={nodes.Mesh_building.geometry} material={materials.roof} />
        <mesh geometry={nodes.Mesh_building_1.geometry} material={materials.dirt} />
        <mesh geometry={nodes.Mesh_building_2.geometry} material={materials.stone} />
      </group>
      <group position={[0.17, 0.63, 0]}>
        <mesh geometry={nodes.Mesh_mill.geometry} material={materials.wood} />
        <mesh geometry={nodes.Mesh_mill_1.geometry} material={materials.sand} />
        <mesh geometry={nodes.Mesh_mill_2.geometry} material={materials.dirt} />
      </group>
      <mesh geometry={nodes.path.geometry} material={materials.dirt} position={[0.3, 0.2, 0.01]} scale={[0.74, 1, 0.74]} />
      <group position={[0.06, 0.2, -0.35]} rotation={[0, 1.31, 0]} scale={0.62}>
        <mesh geometry={nodes.Mesh_tree.geometry} material={materials.foliage} />
        <mesh geometry={nodes.Mesh_tree_1.geometry} material={materials.wood} />
      </group>
      <group position={[-0.25, 0.2, -0.29]} rotation={[0, Math.PI / 6, 0]}>
        <mesh geometry={nodes.Mesh_tree.geometry} material={materials.foliage} />
        <mesh geometry={nodes.Mesh_tree_1.geometry} material={materials.wood} />
      </group>
      <group position={[0.32, 0.2, -0.27]} rotation={[0, 0.15, 0]} scale={0.77}>
        <mesh geometry={nodes.Mesh_tree_2.geometry} material={materials.foliage} />
        <mesh geometry={nodes.Mesh_tree_3.geometry} material={materials.wood} />
      </group>
      <group position={[0, 0.2, 0.35]} rotation={[0, 0.15, 0]} scale={0.77}>
        <mesh geometry={nodes.Mesh_tree_2.geometry} material={materials.foliage} />
        <mesh geometry={nodes.Mesh_tree_3.geometry} material={materials.wood} />
      </group>
    </group>
  )
}

useGLTF.preload('/building_mill.glb')
