/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Building_cabin({ x, y, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/building_cabin.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_building_cabin.geometry} material={materials.dirt} />
      <mesh geometry={nodes.Mesh_building_cabin_1.geometry} material={materials.stone} />
      <group position={[-0.05, 0.37, -0.01]}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh_building.geometry} material={materials.roof} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_building_1.geometry} material={materials.wood} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_building_2.geometry} material={materials.dirt} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.chimney.geometry} material={materials.stone} position={[-0.05, 0.37, -0.2]} />
      <group position={[0.32, 0.2, 0.04]}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh_dock.geometry} material={materials.dirt} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_dock_1.geometry} material={materials.wood} />
      </group>
      <mesh receiveShadow geometry={nodes.rockLarge.geometry} material={materials.stone} position={[0, 0.2, 0]} />
      <group position={[-0.01, 0.28, -0.41]} rotation={[0, 1.31, 0]} scale={0.62}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh_tree.geometry} material={materials.foliage} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_tree_1.geometry} material={materials.wood} />
      </group>
      <group position={[0.26, 0.24, 0.28]} rotation={[0, 1.37, 0]} scale={0.62}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh_tree.geometry} material={materials.foliage} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_tree_1.geometry} material={materials.wood} />
      </group>
      <group position={[-0.01, 0.41, 0.28]} rotation={[0, 0.36, 0]} scale={0.77}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh_tree_2.geometry} material={materials.foliage} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_tree_3.geometry} material={materials.wood} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/building_cabin.glb')
