/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/building_house.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_building_house.geometry} material={materials.dirt} />
      <mesh geometry={nodes.Mesh_building_house_1.geometry} material={materials.grass} />
      <group position={[-0.07, 0.2, 0.14]}>
        <mesh geometry={nodes.Mesh_building.geometry} material={materials.roof} />
        <mesh geometry={nodes.Mesh_building_1.geometry} material={materials.wood} />
        <mesh geometry={nodes.Mesh_building_2.geometry} material={materials.dirt} />
      </group>
      <mesh geometry={nodes.chimney.geometry} material={materials.stone} position={[-0.06, 0.2, -0.05]} />
      <group position={[0.18, 0.2, -0.41]} rotation={[0, -Math.PI / 6, 0]}>
        <mesh geometry={nodes.Mesh_fence.geometry} material={materials.wood} />
        <mesh geometry={nodes.Mesh_fence_1.geometry} material={materials.dirt} />
      </group>
      <mesh geometry={nodes.path.geometry} material={materials.dirt} position={[0.37, 0.2, -0.11]} scale={[0.74, 1, 0.74]} />
      <mesh geometry={nodes.path_1.geometry} material={materials.dirt} position={[0.22, 0.2, 0.06]} rotation={[0, -0.26, 0]} />
      <group position={[0.05, 0.2, -0.3]} rotation={[0, -Math.PI / 6, 0]} scale={0.77}>
        <mesh geometry={nodes.Mesh_tree.geometry} material={materials.foliage} />
        <mesh geometry={nodes.Mesh_tree_1.geometry} material={materials.wood} />
      </group>
      <group position={[-0.23, 0.2, -0.21]}>
        <mesh geometry={nodes.Mesh_tree.geometry} material={materials.foliage} />
        <mesh geometry={nodes.Mesh_tree_1.geometry} material={materials.wood} />
      </group>
      <group position={[0.33, 0.2, 0.27]} rotation={[0, 0.68, 0]} scale={0.77}>
        <mesh geometry={nodes.Mesh_tree.geometry} material={materials.foliage} />
        <mesh geometry={nodes.Mesh_tree_1.geometry} material={materials.wood} />
      </group>
    </group>
  )
}

useGLTF.preload('/building_house.glb')
