/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/building_water.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_building_water.geometry} material={materials.dirt} />
      <mesh geometry={nodes.Mesh_building_water_1.geometry} material={materials.grass} />
      <mesh geometry={nodes.Mesh_building_water_2.geometry} material={materials.wood} />
      <mesh geometry={nodes.Mesh_building_water_3.geometry} material={materials.water} />
      <group position={[-0.04, 0.2, -0.28]}>
        <mesh geometry={nodes.Mesh_building.geometry} material={materials.roof} />
        <mesh geometry={nodes.Mesh_building_1.geometry} material={materials.dirt} />
        <mesh geometry={nodes.Mesh_building_2.geometry} material={materials.wood} />
      </group>
      <mesh geometry={nodes.path.geometry} material={materials.dirt} position={[0.24, 0.2, -0.31]} scale={[0.74, 1, 0.74]} />
      <mesh geometry={nodes.rock.geometry} material={materials.stone} position={[0.37, 0.16, 0.04]} rotation={[0, 1.4, 0]} scale={[0.83, 0.38, 0.83]} />
      <mesh geometry={nodes.rock_1.geometry} material={materials.stone} position={[0.25, 0.16, -0.02]} rotation={[-Math.PI, 1.31, -Math.PI]} scale={[0.83, 0.69, 0.83]} />
      <group position={[0.19, 0.2, 0.34]} rotation={[0, Math.PI / 6, 0]} scale={0.62}>
        <mesh geometry={nodes.Mesh_tree.geometry} material={materials.foliage} />
        <mesh geometry={nodes.Mesh_tree_1.geometry} material={materials.wood} />
      </group>
      <group position={[-0.01, 0.2, 0.34]} rotation={[0, 0.15, 0]} scale={0.77}>
        <mesh geometry={nodes.Mesh_tree.geometry} material={materials.foliage} />
        <mesh geometry={nodes.Mesh_tree_1.geometry} material={materials.wood} />
      </group>
      <group position={[-0.34, 0.2, -0.28]} rotation={[0, Math.PI / 6, 0]} scale={0.62}>
        <mesh geometry={nodes.Mesh_tree.geometry} material={materials.foliage} />
        <mesh geometry={nodes.Mesh_tree_1.geometry} material={materials.wood} />
      </group>
      <mesh geometry={nodes.wheel.geometry} material={materials.wood} position={[-0.05, 0.27, 0]} />
    </group>
  )
}

useGLTF.preload('/building_water.glb')
