/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/building_dock.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_building_dock.geometry} material={materials.dirt} />
      <mesh geometry={nodes.Mesh_building_dock_1.geometry} material={materials.grass} />
      <mesh geometry={nodes.Mesh_building_dock_2.geometry} material={materials.water} />
      <group position={[-0.29, 0.2, -0.14]}>
        <mesh geometry={nodes.Mesh_building.geometry} material={materials.roof} />
        <mesh geometry={nodes.Mesh_building_1.geometry} material={materials.wood} />
        <mesh geometry={nodes.Mesh_building_2.geometry} material={materials.dirt} />
      </group>
      <group position={[0.14, 0.1, 0]}>
        <mesh geometry={nodes.Mesh_dock.geometry} material={materials.wood} />
        <mesh geometry={nodes.Mesh_dock_1.geometry} material={materials.dirt} />
      </group>
      <mesh geometry={nodes.path.geometry} material={materials.dirt} position={[-0.08, 0.2, -0.05]} scale={[0.45, 1, 0.45]} />
      <mesh geometry={nodes.path_1.geometry} material={materials.dirt} position={[-0.11, 0.2, 0.12]} scale={[0.74, 1, 0.74]} />
      <group position={[-0.35, 0.2, 0.17]} rotation={[0, Math.PI / 6, 0]} scale={0.62}>
        <mesh geometry={nodes.Mesh_tree.geometry} material={materials.foliage} />
        <mesh geometry={nodes.Mesh_tree_1.geometry} material={materials.wood} />
      </group>
      <group position={[-0.12, 0.2, 0.29]} rotation={[0, 0.26, 0]} scale={0.77}>
        <mesh geometry={nodes.Mesh_tree.geometry} material={materials.foliage} />
        <mesh geometry={nodes.Mesh_tree_1.geometry} material={materials.wood} />
      </group>
    </group>
  )
}

useGLTF.preload('/building_dock.glb')
