/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/building_tower.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_building_tower.geometry} material={materials.dirt} />
      <mesh geometry={nodes.Mesh_building_tower_1.geometry} material={materials.grass} />
      <mesh geometry={nodes.path.geometry} material={materials.dirt} position={[0.34, 0.2, 0]} scale={[0.74, 1, 0.74]} />
      <mesh geometry={nodes.path_1.geometry} material={materials.dirt} position={[0.24, 0.2, 0.18]} rotation={[0, -0.26, 0]} />
      <mesh geometry={nodes.rock.geometry} material={materials.stone} position={[-0.06, 0.2, -0.23]} rotation={[0, Math.PI / 3, 0]} scale={[0.91, 0.43, 0.9]} />
      <mesh geometry={nodes.rock_1.geometry} material={materials.stone} position={[0.06, 0.2, 0.24]} rotation={[0, Math.PI / 6, 0]} scale={[0.91, 0.43, 0.9]} />
      <mesh geometry={nodes.rock_2.geometry} material={materials.stone} position={[0.13, 0.2, -0.07]} rotation={[0, Math.PI / 6, 0]} scale={[1.66, 0.72, 1.64]} />
      <group position={[0, 0.2, 0]}>
        <mesh geometry={nodes.Mesh_tower.geometry} material={materials.dirt} />
        <mesh geometry={nodes.Mesh_tower_1.geometry} material={materials.stone} />
        <mesh geometry={nodes.Mesh_tower_2.geometry} material={materials.wood} />
        <mesh geometry={nodes.Mesh_tower_3.geometry} material={materials.roof} />
      </group>
      <group position={[-0.32, 0.2, 0.19]} rotation={[0, Math.PI / 6, 0]} scale={0.62}>
        <mesh geometry={nodes.Mesh_tree.geometry} material={materials.foliage} />
        <mesh geometry={nodes.Mesh_tree_1.geometry} material={materials.wood} />
      </group>
      <group position={[0.12, 0.2, 0.37]} rotation={[0, Math.PI / 2, 0]} scale={0.62}>
        <mesh geometry={nodes.Mesh_tree.geometry} material={materials.foliage} />
        <mesh geometry={nodes.Mesh_tree_1.geometry} material={materials.wood} />
      </group>
      <group position={[0, 0.2, -0.41]} rotation={[0, 0.15, 0]} scale={0.77}>
        <mesh geometry={nodes.Mesh_tree.geometry} material={materials.foliage} />
        <mesh geometry={nodes.Mesh_tree_1.geometry} material={materials.wood} />
      </group>
      <group position={[-0.21, 0.2, -0.22]} rotation={[0, -0.66, 0]}>
        <mesh geometry={nodes.Mesh_tree.geometry} material={materials.foliage} />
        <mesh geometry={nodes.Mesh_tree_1.geometry} material={materials.wood} />
      </group>
    </group>
  )
}

useGLTF.preload('/building_tower.glb')
