/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/building_castle.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_building_castle.geometry} material={materials.grass} />
      <mesh geometry={nodes.Mesh_building_castle_1.geometry} material={materials.dirt} />
      <group position={[0, 0.2, 0.43]}>
        <mesh geometry={nodes.Mesh_tower.geometry} material={materials.stone} />
        <mesh geometry={nodes.Mesh_tower_1.geometry} material={materials.stoneDark} />
      </group>
      <group position={[0.38, 0.2, -0.22]}>
        <mesh geometry={nodes.Mesh_tower.geometry} material={materials.stone} />
        <mesh geometry={nodes.Mesh_tower_1.geometry} material={materials.stoneDark} />
      </group>
      <group position={[0.38, 0.2, 0.22]}>
        <mesh geometry={nodes.Mesh_tower.geometry} material={materials.stone} />
        <mesh geometry={nodes.Mesh_tower_1.geometry} material={materials.stoneDark} />
      </group>
      <group position={[-0.38, 0.2, -0.22]}>
        <mesh geometry={nodes.Mesh_tower.geometry} material={materials.stone} />
        <mesh geometry={nodes.Mesh_tower_1.geometry} material={materials.stoneDark} />
      </group>
      <group position={[0, 0.2, -0.43]}>
        <mesh geometry={nodes.Mesh_tower.geometry} material={materials.stone} />
        <mesh geometry={nodes.Mesh_tower_1.geometry} material={materials.stoneDark} />
      </group>
      <group position={[-0.38, 0.2, 0.22]}>
        <mesh geometry={nodes.Mesh_tower.geometry} material={materials.stone} />
        <mesh geometry={nodes.Mesh_tower_1.geometry} material={materials.stoneDark} />
      </group>
      <group position={[-0.13, 0.2, -0.03]} rotation={[0, -0.66, 0]}>
        <mesh geometry={nodes.Mesh_tree.geometry} material={materials.foliage} />
        <mesh geometry={nodes.Mesh_tree_1.geometry} material={materials.wood} />
      </group>
      <group position={[0.11, 0.2, 0.09]} rotation={[0, Math.PI / 6, 0]} scale={0.62}>
        <mesh geometry={nodes.Mesh_tree.geometry} material={materials.foliage} />
        <mesh geometry={nodes.Mesh_tree_1.geometry} material={materials.wood} />
      </group>
      <group position={[0.08, 0.2, -0.22]} rotation={[0, 0.15, 0]} scale={0.77}>
        <mesh geometry={nodes.Mesh_tree.geometry} material={materials.foliage} />
        <mesh geometry={nodes.Mesh_tree_1.geometry} material={materials.wood} />
      </group>
      <group position={[0, 0.2, 0]}>
        <mesh geometry={nodes.Mesh_wall.geometry} material={materials.stoneDark} />
        <mesh geometry={nodes.Mesh_wall_1.geometry} material={materials.stone} />
      </group>
    </group>
  )
}

useGLTF.preload('/building_castle.glb')
