/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/building_market.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_building_market.geometry} material={materials.grass} />
      <mesh geometry={nodes.Mesh_building_market_1.geometry} material={materials.dirt} />
      <mesh geometry={nodes.Mesh_building_market_2.geometry} material={materials.stone} />
      <mesh geometry={nodes.crate.geometry} material={materials.dirt} position={[0.41, 0.2, 0.13]} rotation={[-Math.PI, Math.PI / 6, -Math.PI]} scale={1.26} />
      <mesh geometry={nodes.crate_1.geometry} material={materials.dirt} position={[-0.21, 0.2, 0.09]} rotation={[-Math.PI, Math.PI / 6, -Math.PI]} scale={1.26} />
      <mesh geometry={nodes.fence.geometry} material={materials.dirt} position={[0.19, 0.2, -0.32]} rotation={[-Math.PI, Math.PI / 6, -Math.PI]} />
      <group position={[0.24, 0.2, 0.23]} rotation={[0, -Math.PI / 3, 0]}>
        <mesh geometry={nodes.Mesh_stall.geometry} material={materials.dirt} />
        <mesh geometry={nodes.Mesh_stall_1.geometry} material={materials.roof} />
      </group>
      <group position={[-0.32, 0.2, -0.09]}>
        <mesh geometry={nodes.Mesh_stall.geometry} material={materials.dirt} />
        <mesh geometry={nodes.Mesh_stall_1.geometry} material={materials.roof} />
      </group>
      <group position={[-0.24, 0.2, 0.22]}>
        <mesh geometry={nodes.Mesh_tree.geometry} material={materials.foliage} />
        <mesh geometry={nodes.Mesh_tree_1.geometry} material={materials.wood} />
      </group>
      <group position={[-0.19, 0.2, -0.38]} rotation={[0, -Math.PI / 6, 0]} scale={0.77}>
        <mesh geometry={nodes.Mesh_tree.geometry} material={materials.foliage} />
        <mesh geometry={nodes.Mesh_tree_1.geometry} material={materials.wood} />
      </group>
      <group position={[-0.01, 0.2, 0.34]} rotation={[0, -Math.PI / 6, 0]} scale={0.77}>
        <mesh geometry={nodes.Mesh_tree.geometry} material={materials.foliage} />
        <mesh geometry={nodes.Mesh_tree_1.geometry} material={materials.wood} />
      </group>
      <group position={[0, 0.2, 0]} scale={[1, 0.88, 1]}>
        <mesh geometry={nodes.Mesh_well.geometry} material={materials.stone} />
        <mesh geometry={nodes.Mesh_well_1.geometry} material={materials.water} />
      </group>
    </group>
  )
}

useGLTF.preload('/building_market.glb')
