/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/dirt_lumber.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.dirt_lumber.geometry} material={materials.dirt}>
        <group position={[-0.2, 0.1, 0.16]}>
          <group position={[-0.08, 0, 0.16]}>
            <mesh geometry={nodes.Mesh_OuterShell.geometry} material={materials.wood} />
            <mesh geometry={nodes.Mesh_OuterShell_1.geometry} material={materials.dirt} />
          </group>
        </group>
        <group position={[0.1, 0.1, -0.39]} rotation={[Math.PI, -0.98, Math.PI]} scale={0.5}>
          <mesh geometry={nodes.Mesh_log.geometry} material={materials.wood} />
          <mesh geometry={nodes.Mesh_log_1.geometry} material={materials.dirt} />
        </group>
        <group position={[0.16, 0.1, 0.27]} rotation={[0, Math.PI / 4, 0]}>
          <mesh geometry={nodes.Mesh_tree.geometry} material={materials.foliage} />
          <mesh geometry={nodes.Mesh_tree_1.geometry} material={materials.wood} />
        </group>
        <group position={[-0.05, 0.1, 0.39]} rotation={[0, 1, 0]} scale={0.62}>
          <mesh geometry={nodes.Mesh_tree.geometry} material={materials.foliage} />
          <mesh geometry={nodes.Mesh_tree_1.geometry} material={materials.wood} />
        </group>
        <group position={[-0.35, 0.1, -0.11]} rotation={[0, 1.2, 0]} scale={0.77}>
          <mesh geometry={nodes.Mesh_tree_2.geometry} material={materials.foliage} />
          <mesh geometry={nodes.Mesh_tree_3.geometry} material={materials.wood} />
        </group>
        <group position={[0.35, 0.1, -0.22]} rotation={[0, Math.PI / 6, 0]} scale={0.77}>
          <mesh geometry={nodes.Mesh_tree_4.geometry} material={materials.foliage} />
          <mesh geometry={nodes.Mesh_tree_5.geometry} material={materials.wood} />
        </group>
        <group position={[-0.2, 0.1, -0.31]} rotation={[0, Math.PI / 2, 0]} scale={0.62}>
          <mesh geometry={nodes.Mesh_tree_6.geometry} material={materials.foliage} />
          <mesh geometry={nodes.Mesh_tree_7.geometry} material={materials.wood} />
        </group>
      </mesh>
    </group>
  )
}

useGLTF.preload('/dirt_lumber.glb')
