/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/grass_hill.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_grass_hill.geometry} material={materials.dirt} />
      <mesh geometry={nodes.Mesh_grass_hill_1.geometry} material={materials.grass} />
      <group position={[0, 0.2, -0.02]} rotation={[0, Math.PI / 3, 0]} scale={[0.86, 0.85, 0.91]}>
        <mesh geometry={nodes.Mesh_rockLarge.geometry} material={materials.stone} />
        <mesh geometry={nodes.Mesh_rockLarge_1.geometry} material={materials._defaultMat} />
      </group>
      <group position={[-0.32, 0.2, 0.19]} rotation={[0, Math.PI / 6, 0]} scale={0.62}>
        <mesh geometry={nodes.Mesh_tree.geometry} material={materials.foliage} />
        <mesh geometry={nodes.Mesh_tree_1.geometry} material={materials.wood} />
      </group>
      <group position={[0.1, 0.56, -0.01]} rotation={[0, 1.15, 0]} scale={0.62}>
        <mesh geometry={nodes.Mesh_tree.geometry} material={materials.foliage} />
        <mesh geometry={nodes.Mesh_tree_1.geometry} material={materials.wood} />
      </group>
      <group position={[0.01, 0.28, -0.3]} rotation={[0, Math.PI / 6, 0]} scale={0.62}>
        <mesh geometry={nodes.Mesh_tree.geometry} material={materials.foliage} />
        <mesh geometry={nodes.Mesh_tree_1.geometry} material={materials.wood} />
      </group>
      <group position={[0.36, 0.2, 0.24]} rotation={[0, Math.PI / 2, 0]} scale={0.62}>
        <mesh geometry={nodes.Mesh_tree.geometry} material={materials.foliage} />
        <mesh geometry={nodes.Mesh_tree_1.geometry} material={materials.wood} />
      </group>
    </group>
  )
}

useGLTF.preload('/grass_hill.glb')
