/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/sand.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_sand.geometry} material={materials.dirt} />
      <mesh geometry={nodes.Mesh_sand_1.geometry} material={materials.sand} />
    </group>
  )
}

useGLTF.preload('/sand.glb')
