/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/sand_rocks.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_sand_rocks.geometry} material={materials.dirt} />
      <mesh geometry={nodes.Mesh_sand_rocks_1.geometry} material={materials.sand} />
      <mesh geometry={nodes.rock.geometry} material={materials.sand} position={[-0.06, 0.2, 0.21]} scale={[0.69, 0.33, 0.69]} />
      <mesh geometry={nodes.rock_1.geometry} material={materials.sand} position={[-0.38, 0.2, 0.18]} rotation={[0, Math.PI / 6, 0]} scale={[0.91, 0.43, 0.9]} />
      <mesh geometry={nodes.rock_2.geometry} material={materials.sand} position={[-0.36, 0.2, 0.05]} scale={[0.69, 0.33, 0.69]} />
      <mesh geometry={nodes.rock_3.geometry} material={materials.sand} position={[0.02, 0.2, -0.42]} rotation={[0, 0.26, 0]} scale={[0.69, 0.33, 0.69]} />
      <mesh geometry={nodes.rock_4.geometry} material={materials.sand} position={[0.38, 0.2, 0.22]} rotation={[0, -0.91, 0]} scale={[0.91, 0.43, 0.9]} />
    </group>
  )
}

useGLTF.preload('/sand_rocks.glb')
