/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/stone_rocks.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_stone_rocks.geometry} material={materials.dirt} />
      <mesh geometry={nodes.Mesh_stone_rocks_1.geometry} material={materials.stone} />
      <mesh geometry={nodes.rock.geometry} material={materials.stone} position={[-0.34, 0.2, -0.19]} rotation={[0, Math.PI / 6, 0]} scale={[0.91, 0.43, 0.9]} />
      <mesh geometry={nodes.rock_1.geometry} material={materials.stone} position={[0.35, 0.2, 0.21]} rotation={[0, Math.PI / 6, 0]} scale={[0.91, 0.43, 0.9]} />
      <mesh geometry={nodes.rockLarge.geometry} material={materials.stone} position={[-0.04, 0.2, 0.27]} rotation={[-Math.PI, 1.43, -Math.PI]} scale={[0.5, 0.49, 0.53]} />
      <mesh geometry={nodes.rockLarge_1.geometry} material={materials.stone} position={[0.05, 0.2, -0.26]} />
    </group>
  )
}

useGLTF.preload('/stone_rocks.glb')
