/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/stone_hill.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_stone_hill.geometry} material={materials.dirt} />
      <mesh geometry={nodes.Mesh_stone_hill_1.geometry} material={materials.stone} />
      <mesh geometry={nodes.rockLarge.geometry} material={materials.stone} position={[0, 0.2, 0]} scale={[1, 0.5, 1]} />
    </group>
  )
}

useGLTF.preload('/stone_hill.glb')
