/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/unit_boat.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.unit_boat.geometry} material={materials.dirt}>
        <mesh geometry={nodes.Group.geometry} material={materials.dirt} position={[-0.13, 0.12, -0.09]} rotation={[-Math.PI / 4, 0, -Math.PI / 2]} scale={[0.21, 0.43, 0.29]} />
        <mesh geometry={nodes.Group_1.geometry} material={materials.dirt} position={[0.11, 0.12, -0.09]} rotation={[-Math.PI / 4, 0, -Math.PI / 2]} scale={[0.21, 0.43, 0.29]} />
        <mesh geometry={nodes.Group_2.geometry} material={materials.dirt} position={[-0.02, 0.12, 0.09]} rotation={[-2.36, 0, -Math.PI / 2]} scale={[-0.21, 0.43, 0.29]} />
        <mesh geometry={nodes.Group_3.geometry} material={materials.dirt} position={[-0.13, 0.12, 0.09]} rotation={[-2.36, 0, -Math.PI / 2]} scale={[-0.21, 0.43, 0.29]} />
        <mesh geometry={nodes.Group_4.geometry} material={materials.dirt} position={[0.11, 0.12, 0.09]} rotation={[-2.36, 0, -Math.PI / 2]} scale={[-0.21, 0.43, 0.29]} />
        <mesh geometry={nodes.Group_5.geometry} material={materials.dirt} position={[-0.02, 0.12, -0.09]} rotation={[-Math.PI / 4, 0, -Math.PI / 2]} scale={[0.21, 0.43, 0.29]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/unit_boat.glb')
