/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/unit_tower.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_unit_tower.geometry} material={materials.stone} />
      <mesh geometry={nodes.Mesh_unit_tower_1.geometry} material={materials.dirt} />
      <mesh geometry={nodes.Mesh_unit_tower_2.geometry} material={materials.wood} />
      <mesh geometry={nodes.Mesh_unit_tower_3.geometry} material={materials.roof} />
    </group>
  )
}

useGLTF.preload('/unit_tower.glb')
