/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/unit_tree.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_unit_tree.geometry} material={materials.wood} />
      <mesh geometry={nodes.Mesh_unit_tree_1.geometry} material={materials.foliage} />
    </group>
  )
}

useGLTF.preload('/unit_tree.glb')
