/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/unit_house.glb')
  return (
    <group scale={0.5} rotation={[0, 0.4, 0]} ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Mesh_unit_house.geometry} material={materials.roof} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_unit_house_1.geometry} material={materials.dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_unit_house_2.geometry} material={materials.wood} />
    </group>
  )
}

useGLTF.preload('/models/unit_house.glb')
