/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/unit_wallTower.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_unit_wallTower.geometry} material={materials.stone} />
      <mesh geometry={nodes.Mesh_unit_wallTower_1.geometry} material={materials.stoneDark} />
    </group>
  )
}

useGLTF.preload('/unit_wallTower.glb')
