/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/unit_houseLarge.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_unit_houseLarge.geometry} material={materials.wood} />
      <mesh geometry={nodes.Mesh_unit_houseLarge_1.geometry} material={materials.roof} />
      <mesh geometry={nodes.Mesh_unit_houseLarge_2.geometry} material={materials.dirt} />
    </group>
  )
}

useGLTF.preload('/unit_houseLarge.glb')
