/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/unit_mill.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_unit_mill.geometry} material={materials.roof} />
      <mesh geometry={nodes.Mesh_unit_mill_1.geometry} material={materials.stone} />
      <mesh geometry={nodes.Mesh_unit_mill_2.geometry} material={materials.dirt} />
      <group position={[0.17, 0.42, 0]}>
        <mesh geometry={nodes.Mesh_mill.geometry} material={materials.wood} />
        <mesh geometry={nodes.Mesh_mill_1.geometry} material={materials.sand} />
        <mesh geometry={nodes.Mesh_mill_2.geometry} material={materials.dirt} />
      </group>
    </group>
  )
}

useGLTF.preload('/unit_mill.glb')
