/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

import { WaterMaterial } from '../materials';

export const Water = React.forwardRef((props, ref) => {
  const { nodes } = useGLTF('/models/water.glb')
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh receiveShadow geometry={nodes.water.geometry}>
        <WaterMaterial/>
      </mesh>
    </group>
  )
});

useGLTF.preload('/models/water.glb')
