/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/water_island.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_water_island.geometry} material={materials.water} />
      <mesh geometry={nodes.Mesh_water_island_1.geometry} material={materials.sand} />
      <mesh geometry={nodes.Mesh_water_island_2.geometry} material={materials.dirt} />
      <mesh geometry={nodes.rock.geometry} material={materials.sand} position={[0.17, 0.2, 0.1]} scale={[0.69, 0.33, 0.69]} />
      <mesh geometry={nodes.rock_1.geometry} material={materials.sand} position={[-0.15, 0.2, 0.07]} rotation={[0, Math.PI / 6, 0]} scale={[0.91, 0.43, 0.9]} />
      <mesh geometry={nodes.rock_2.geometry} material={materials.sand} position={[-0.13, 0.2, -0.06]} scale={[0.69, 0.33, 0.69]} />
    </group>
  )
}

useGLTF.preload('/water_island.glb')
