/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

import { WaterMaterial } from '../materials';

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/water_rocks.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh receiveShadow geometry={nodes.water_rocks.geometry}>
        <WaterMaterial/>
        <mesh castShadow receiveShadow geometry={nodes.rock.geometry} material={materials.stone} position={[0.1, 0.1, -0.35]} rotation={[0, Math.PI / 2, 0]} scale={[0.91, 0.43, 0.9]} />
        <mesh castShadow receiveShadow geometry={nodes.rock_1.geometry} material={materials.stone} position={[-0.05, 0.1, -0.41]} rotation={[0, Math.PI / 3, 0]} scale={[0.91, 0.87, 0.9]} />
        <mesh castShadow receiveShadow geometry={nodes.rock_2.geometry} material={materials.stone} position={[-0.34, 0.1, -0.19]} rotation={[0, Math.PI / 6, 0]} scale={[0.91, 0.43, 0.9]} />
        <mesh castShadow receiveShadow geometry={nodes.rock_3.geometry} material={materials.stone} position={[0.05, 0.1, 0.08]} rotation={[-Math.PI, 1.31, -Math.PI]} scale={[0.91, 0.43, 0.9]} />
        <mesh castShadow receiveShadow geometry={nodes.rock_4.geometry} material={materials.stone} position={[0.35, 0.1, 0.21]} rotation={[0, Math.PI / 6, 0]} scale={[0.91, 0.43, 0.9]} />
        <mesh castShadow receiveShadow geometry={nodes.rockLarge.geometry} material={materials.stone} position={[-0.36, 0.1, 0.19]} rotation={[Math.PI, -0.26, Math.PI]} scale={0.49} />
        <mesh castShadow receiveShadow geometry={nodes.rockLarge_1.geometry} material={materials.stone} position={[-0.02, 0.1, 0.3]} scale={0.73} />
        <mesh castShadow receiveShadow geometry={nodes.rockLarge_2.geometry} material={materials.stone} position={[-0.08, 0.1, -0.17]} scale={0.69} />
        <mesh castShadow receiveShadow geometry={nodes.rockLarge_3.geometry} material={materials.stone} position={[0.33, 0.1, -0.2]} rotation={[0, -Math.PI / 4, 0]} scale={0.52} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/water_rocks.glb')
