/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

import { WaterMaterial } from '../materials';

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes } = useGLTF('/models/water.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh receiveShadow geometry={nodes.water.geometry}>
        <WaterMaterial/>
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/water.glb')
